import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    appName: "Medi Trust",
    tagline: "Health Care You Can Trust",
    welcome: "Welcome",
    selectLanguage: "Select Language",
    selectRole: "Select Account Type",
    patient: "Patient",
    doctor: "Doctor",
    pharmacy: "Pharmacy",
    login: "Login",
    email: "Email",
    password: "Password",
    signInWithGoogle: "Sign in with Google",
    watchDemo: "Watch Demo Video",
    home: "Home",
    chatAssistant: "Chat Assistant",
    symptomChecker: "Symptom Checker",
    skinScanner: "Skin Scanner",
    findDoctors: "Find Doctors",
    pharmacies: "Pharmacies",
    appointments: "My Appointments",
    prescriptions: "Prescriptions",
    profile: "Profile",
    settings: "Settings",
    logout: "Logout",
    bookNow: "Book Now",
    offline: "Offline Visit",
    online: "Online Consultation",
    chat: "Chat",
    audio: "Audio Call",
    video: "Video Call",
    disclaimer: "This is a demonstration prototype. AI responses are informational only and not medical diagnosis. Consult a licensed doctor for treatment.",
    aiDisclaimer: "AI suggestions are for informational purposes only.",
    consultDoctor: "Consult a Doctor",
    enterSymptoms: "Enter your symptoms",
    possibleConditions: "Possible Conditions",
    severity: "Severity Level",
    suggestedSpecialist: "Suggested Specialist",
    myAppointments: "My Appointments",
    manageProfile: "Manage Profile",
    setFees: "Set Consultation Fees",
    writePrescription: "Write Prescription",
    viewAnalytics: "View Analytics",
    pending: "Pending",
    confirmed: "Confirmed",
    completed: "Completed",
    cancelled: "Cancelled",
    processing: "Processing",
    ready: "Ready for Pickup",
    delivered: "Delivered",
    viewPrescription: "View Prescription",
    orderMedicines: "Order Medicines",
    verified: "Verified",
    experience: "years experience",
    rating: "Rating",
    consultationFee: "Consultation Fee",
    selectDate: "Select Date",
    selectTime: "Select Time Slot",
    confirmBooking: "Confirm Booking",
    cancel: "Cancel",
    save: "Save",
    submit: "Submit",
    loading: "Loading...",
    noData: "No data available",
    dashboard: "Dashboard",
    totalPatients: "Total Patients",
    todayAppointments: "Today's Appointments",
    totalEarnings: "Total Earnings",
    pendingOrders: "Pending Orders",
    completedOrders: "Completed Orders",
    medicine: "Medicine",
    dosage: "Dosage",
    frequency: "Frequency",
    duration: "Duration",
    instructions: "Instructions",
    diagnosis: "Diagnosis",
    additionalNotes: "Additional Notes",
    generatePdf: "Generate PDF",
    downloadPrescription: "Download Prescription"
  },
  hi: {
    appName: "मेडी ट्रस्ट",
    tagline: "विश्वसनीय स्वास्थ्य सेवा",
    welcome: "स्वागत है",
    selectLanguage: "भाषा चुनें",
    selectRole: "खाता प्रकार चुनें",
    patient: "मरीज",
    doctor: "डॉक्टर",
    pharmacy: "फार्मेसी",
    login: "लॉगिन",
    email: "ईमेल",
    password: "पासवर्ड",
    signInWithGoogle: "Google से साइन इन करें",
    watchDemo: "डेमो वीडियो देखें",
    home: "होम",
    chatAssistant: "चैट सहायक",
    symptomChecker: "लक्षण जांच",
    skinScanner: "स्किन स्कैनर",
    findDoctors: "डॉक्टर खोजें",
    pharmacies: "फार्मेसियां",
    appointments: "मेरी अपॉइंटमेंट्स",
    prescriptions: "प्रिस्क्रिप्शन",
    profile: "प्रोफाइल",
    settings: "सेटिंग्स",
    logout: "लॉगआउट",
    bookNow: "अभी बुक करें",
    offline: "ऑफलाइन विजिट",
    online: "ऑनलाइन परामर्श",
    chat: "चैट",
    audio: "ऑडियो कॉल",
    video: "वीडियो कॉल",
    disclaimer: "यह एक प्रदर्शन प्रोटोटाइप है। AI प्रतिक्रियाएं केवल जानकारी के लिए हैं। उपचार के लिए लाइसेंस प्राप्त डॉक्टर से परामर्श करें।",
    aiDisclaimer: "AI सुझाव केवल सूचनात्मक उद्देश्यों के लिए हैं।",
    consultDoctor: "डॉक्टर से परामर्श करें",
    enterSymptoms: "अपने लक्षण दर्ज करें",
    possibleConditions: "संभावित स्थितियां",
    severity: "गंभीरता स्तर",
    suggestedSpecialist: "सुझाए गए विशेषज्ञ",
    myAppointments: "मेरी अपॉइंटमेंट्स",
    manageProfile: "प्रोफाइल प्रबंधित करें",
    setFees: "परामर्श शुल्क सेट करें",
    writePrescription: "प्रिस्क्रिप्शन लिखें",
    viewAnalytics: "एनालिटिक्स देखें",
    pending: "लंबित",
    confirmed: "पुष्टि",
    completed: "पूर्ण",
    cancelled: "रद्द",
    processing: "प्रोसेसिंग",
    ready: "पिकअप के लिए तैयार",
    delivered: "डिलीवर किया गया",
    viewPrescription: "प्रिस्क्रिप्शन देखें",
    orderMedicines: "दवाइयां ऑर्डर करें",
    verified: "सत्यापित",
    experience: "वर्ष अनुभव",
    rating: "रेटिंग",
    consultationFee: "परामर्श शुल्क",
    selectDate: "तारीख चुनें",
    selectTime: "समय स्लॉट चुनें",
    confirmBooking: "बुकिंग की पुष्टि करें",
    cancel: "रद्द करें",
    save: "सेव करें",
    submit: "जमा करें",
    loading: "लोड हो रहा है...",
    noData: "कोई डेटा उपलब्ध नहीं",
    dashboard: "डैशबोर्ड",
    totalPatients: "कुल मरीज",
    todayAppointments: "आज की अपॉइंटमेंट्स",
    totalEarnings: "कुल कमाई",
    pendingOrders: "लंबित ऑर्डर",
    completedOrders: "पूर्ण ऑर्डर",
    medicine: "दवाई",
    dosage: "खुराक",
    frequency: "आवृत्ति",
    duration: "अवधि",
    instructions: "निर्देश",
    diagnosis: "निदान",
    additionalNotes: "अतिरिक्त नोट्स",
    generatePdf: "PDF बनाएं",
    downloadPrescription: "प्रिस्क्रिप्शन डाउनलोड करें"
  },
  te: {
    appName: "మెడి ట్రస్ట్",
    tagline: "మీరు నమ్మగల ఆరోగ్య సంరక్షణ",
    welcome: "స్వాగతం",
    selectLanguage: "భాష ఎంచుకోండి",
    selectRole: "ఖాతా రకం ఎంచుకోండి",
    patient: "రోగి",
    doctor: "డాక్టర్",
    pharmacy: "ఫార్మసీ",
    login: "లాగిన్",
    email: "ఇమెయిల్",
    password: "పాస్వర్డ్",
    signInWithGoogle: "Google తో సైన్ ఇన్ చేయండి",
    watchDemo: "డెమో వీడియో చూడండి",
    home: "హోమ్",
    chatAssistant: "చాట్ అసిస్టెంట్",
    symptomChecker: "లక్షణాల తనిఖీ",
    skinScanner: "స్కిన్ స్కానర్",
    findDoctors: "డాక్టర్లను కనుగొనండి",
    pharmacies: "ఫార్మసీలు",
    appointments: "నా అపాయింట్మెంట్లు",
    prescriptions: "ప్రిస్క్రిప్షన్లు",
    profile: "ప్రొఫైల్",
    settings: "సెట్టింగ్లు",
    logout: "లాగ్అవుట్",
    bookNow: "ఇప్పుడు బుక్ చేయండి",
    offline: "ఆఫ్లైన్ సందర్శన",
    online: "ఆన్లైన్ సంప్రదింపు",
    chat: "చాట్",
    audio: "ఆడియో కాల్",
    video: "వీడియో కాల్",
    disclaimer: "ఇది ప్రదర్శన ప్రోటోటైప్. AI ప్రతిస్పందనలు సమాచార ప్రయోజనాల కోసం మాత్రమే. చికిత్స కోసం లైసెన్స్ పొందిన వైద్యుడిని సంప్రదించండి.",
    aiDisclaimer: "AI సూచనలు సమాచార ప్రయోజనాల కోసం మాత్రమే.",
    consultDoctor: "డాక్టర్ని సంప్రదించండి",
    enterSymptoms: "మీ లక్షణాలను నమోదు చేయండి",
    possibleConditions: "సాధ్యమైన పరిస్థితులు",
    severity: "తీవ్రత స్థాయి",
    suggestedSpecialist: "సూచించిన నిపుణులు",
    myAppointments: "నా అపాయింట్మెంట్లు",
    manageProfile: "ప్రొఫైల్ నిర్వహించండి",
    setFees: "సంప్రదింపు ఫీజులు సెట్ చేయండి",
    writePrescription: "ప్రిస్క్రిప్షన్ రాయండి",
    viewAnalytics: "విశ్లేషణలు చూడండి",
    pending: "పెండింగ్",
    confirmed: "నిర్ధారించబడింది",
    completed: "పూర్తయింది",
    cancelled: "రద్దు చేయబడింది",
    processing: "ప్రాసెసింగ్",
    ready: "పికప్ కోసం సిద్ధంగా ఉంది",
    delivered: "డెలివరీ అయింది",
    viewPrescription: "ప్రిస్క్రిప్షన్ చూడండి",
    orderMedicines: "మందులు ఆర్డర్ చేయండి",
    verified: "ధృవీకరించబడింది",
    experience: "సంవత్సరాల అనుభవం",
    rating: "రేటింగ్",
    consultationFee: "సంప్రదింపు ఫీజు",
    selectDate: "తేదీ ఎంచుకోండి",
    selectTime: "సమయ స్లాట్ ఎంచుకోండి",
    confirmBooking: "బుకింగ్ నిర్ధారించండి",
    cancel: "రద్దు చేయండి",
    save: "సేవ్ చేయండి",
    submit: "సమర్పించండి",
    loading: "లోడ్ అవుతోంది...",
    noData: "డేటా అందుబాటులో లేదు",
    dashboard: "డాష్బోర్డ్",
    totalPatients: "మొత్తం రోగులు",
    todayAppointments: "ఈరోజు అపాయింట్మెంట్లు",
    totalEarnings: "మొత్తం ఆదాయం",
    pendingOrders: "పెండింగ్ ఆర్డర్లు",
    completedOrders: "పూర్తయిన ఆర్డర్లు",
    medicine: "మందు",
    dosage: "మోతాదు",
    frequency: "ఫ్రీక్వెన్సీ",
    duration: "వ్యవధి",
    instructions: "సూచనలు",
    diagnosis: "రోగ నిర్ధారణ",
    additionalNotes: "అదనపు గమనికలు",
    generatePdf: "PDF రూపొందించండి",
    downloadPrescription: "ప్రిస్క్రిప్షన్ డౌన్లోడ్ చేయండి"
  },
  ta: {
    appName: "மெடி ட்ரஸ்ட்",
    tagline: "நம்பகமான சுகாதார சேவை",
    welcome: "வரவேற்கிறோம்",
    selectLanguage: "மொழியை தேர்ந்தெடுக்கவும்",
    selectRole: "கணக்கு வகையை தேர்ந்தெடுக்கவும்",
    patient: "நோயாளி",
    doctor: "மருத்துவர்",
    pharmacy: "மருந்தகம்",
    login: "உள்நுழைவு",
    email: "மின்னஞ்சல்",
    password: "கடவுச்சொல்",
    signInWithGoogle: "Google மூலம் உள்நுழையவும்",
    watchDemo: "டெமோ வீடியோ பார்க்கவும்",
    home: "முகப்பு",
    chatAssistant: "சாட் உதவியாளர்",
    symptomChecker: "அறிகுறி சோதனை",
    skinScanner: "தோல் ஸ்கேனர்",
    findDoctors: "மருத்துவர்களை கண்டுபிடி",
    pharmacies: "மருந்தகங்கள்",
    appointments: "எனது சந்திப்புகள்",
    prescriptions: "மருந்துச்சீட்டுகள்",
    profile: "சுயவிவரம்",
    settings: "அமைப்புகள்",
    logout: "வெளியேறு",
    bookNow: "இப்போது பதிவு செய்யுங்கள்",
    offline: "ஆஃப்லைன் வருகை",
    online: "ஆன்லைன் ஆலோசனை",
    chat: "சாட்",
    audio: "ஆடியோ அழைப்பு",
    video: "வீடியோ அழைப்பு",
    disclaimer: "இது ஒரு செயல்விளக்க முன்மாதிரி. AI பதில்கள் தகவல் நோக்கங்களுக்கு மட்டுமே. சிகிச்சைக்கு உரிமம் பெற்ற மருத்துவரை அணுகவும்.",
    aiDisclaimer: "AI பரிந்துரைகள் தகவல் நோக்கங்களுக்கு மட்டுமே.",
    consultDoctor: "மருத்துவரை அணுகவும்",
    enterSymptoms: "உங்கள் அறிகுறிகளை உள்ளிடவும்",
    possibleConditions: "சாத்தியமான நிலைகள்",
    severity: "தீவிர நிலை",
    suggestedSpecialist: "பரிந்துரைக்கப்பட்ட நிபுணர்",
    myAppointments: "எனது சந்திப்புகள்",
    manageProfile: "சுயவிவரத்தை நிர்வகி",
    setFees: "ஆலோசனை கட்டணங்களை அமை",
    writePrescription: "மருந்துச்சீட்டு எழுது",
    viewAnalytics: "பகுப்பாய்வு பார்",
    pending: "நிலுவையில்",
    confirmed: "உறுதிசெய்யப்பட்டது",
    completed: "முடிந்தது",
    cancelled: "ரத்து செய்யப்பட்டது",
    processing: "செயலாக்கம்",
    ready: "எடுக்க தயார்",
    delivered: "வழங்கப்பட்டது",
    viewPrescription: "மருந்துச்சீட்டு பார்",
    orderMedicines: "மருந்துகளை ஆர்டர் செய்",
    verified: "சரிபார்க்கப்பட்டது",
    experience: "ஆண்டுகள் அனுபவம்",
    rating: "மதிப்பீடு",
    consultationFee: "ஆலோசனை கட்டணம்",
    selectDate: "தேதியை தேர்ந்தெடுக்கவும்",
    selectTime: "நேர இடைவெளியை தேர்ந்தெடுக்கவும்",
    confirmBooking: "பதிவை உறுதிசெய்யவும்",
    cancel: "ரத்து செய்",
    save: "சேமி",
    submit: "சமர்ப்பி",
    loading: "ஏற்றுகிறது...",
    noData: "தரவு கிடைக்கவில்லை",
    dashboard: "டாஷ்போர்டு",
    totalPatients: "மொத்த நோயாளிகள்",
    todayAppointments: "இன்றைய சந்திப்புகள்",
    totalEarnings: "மொத்த வருவாய்",
    pendingOrders: "நிலுவை ஆர்டர்கள்",
    completedOrders: "முடிந்த ஆர்டர்கள்",
    medicine: "மருந்து",
    dosage: "அளவு",
    frequency: "அடிக்கடி",
    duration: "காலம்",
    instructions: "வழிமுறைகள்",
    diagnosis: "நோய் கண்டறிதல்",
    additionalNotes: "கூடுதல் குறிப்புகள்",
    generatePdf: "PDF உருவாக்கு",
    downloadPrescription: "மருந்துச்சீட்டு பதிவிறக்கம்"
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('meditrust_language');
    if (savedLang) {
      setLanguage(savedLang);
    }
  }, []);

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('meditrust_language', lang);
  };

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, translations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export default LanguageContext;